# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

FACEBOOK_KEY: 433312300089516
FACEBOOK_SECRET: 6e5d8dc6f680a4d9b9b40004166f659a

TWITTER_KEY: muekOMJXBKXRWEUnVGG0pA
TWITTER_SECRET: PtUsO6guIPDPn9x4OUQQGvU6yGqD8fswEiAoECBOq4

GOOGLE_KEY: 759053607189.apps.googleusercontent.com
GOOGLE_SECRET: 1Z8PJatEWV-q0oJ3jgm3IvSr